import inquirer from 'inquirer';
import chalk from 'chalk';
import path from 'path';
import fs from 'fs';
import { createDataLake } from '../database';

interface InitOptions {
  path: string;
}

export async function initCommand(options: InitOptions) {
  try {
    console.log(chalk.blue('🚀 Initializing Carbonara project...'));
    
    const projectPath = path.resolve(options.path);
    
    // Check if directory exists
    if (!fs.existsSync(projectPath)) {
      fs.mkdirSync(projectPath, { recursive: true });
    }

    // Get project details
    const answers = await inquirer.prompt([
      {
        type: 'input',
        name: 'name',
        message: 'Project name:',
        default: path.basename(projectPath),
        validate: (input: string) => input.length > 0 ? true : 'Project name is required'
      },
      {
        type: 'input',
        name: 'description',
        message: 'Project description:',
        default: 'A Carbonara CO2 assessment project'
      },
      {
        type: 'list',
        name: 'projectType',
        message: 'Project type:',
        choices: [
          { name: 'Web Application', value: 'web' },
          { name: 'Mobile Application', value: 'mobile' },
          { name: 'Desktop Application', value: 'desktop' },
          { name: 'API/Backend Service', value: 'api' },
          { name: 'Other', value: 'other' }
        ]
      }
    ]);

    // Initialize database
    const dataLake = createDataLake({
      dbPath: path.join(projectPath, 'carbonara.db')
    });
    
    await dataLake.initialize();
    
    // Create project in database
    const projectId = await dataLake.createProject(
      answers.name,
      projectPath,
      {
        description: answers.description,
        projectType: answers.projectType,
        initialized: new Date().toISOString()
      }
    );

    // Create carbonara config file
    const config = {
      name: answers.name,
      description: answers.description,
      projectType: answers.projectType,
      projectId,
      database: {
        path: 'carbonara.db'
      },
      tools: {
        greenframe: {
          enabled: true
        }
      }
    };

    fs.writeFileSync(
      path.join(projectPath, 'carbonara.config.json'),
      JSON.stringify(config, null, 2)
    );

    // Create .mega-linter.yml configuration file
    const megalinterConfig = `# MegaLinter Configuration File
# Generated by Carbonara CLI

# Activation and Scope
VALIDATE_ALL_CODEBASE: true
APPLY_FIXES: none
DISABLE: []
ENABLE: []
DISABLE_LINTERS: []
ENABLE_LINTERS: []

# File Filtering
FILTER_REGEX_EXCLUDE: none
FILTER_REGEX_INCLUDE: all
IGNORE_GENERATED_FILES: false
IGNORE_GITIGNORED_FILES: true

# Workspace and Reporting
DEFAULT_WORKSPACE: /tmp/lint
REPORT_OUTPUT_FOLDER: megalinter-reports
CLEAR_REPORT_FOLDER: false

# Linter Configurations
LINTER_RULES_PATH: .github/linters
FAIL_IF_MISSING_LINTER_IN_FLAVOR: false
FAIL_IF_UPDATED_SOURCES: false

# Style Defaults
JAVASCRIPT_DEFAULT_STYLE: standard
MARKDOWN_DEFAULT_STYLE: markdownlint
PYTHON_DEFAULT_STYLE: black
TYPESCRIPT_DEFAULT_STYLE: standard

# Performance and Logging
PARALLEL: true
LOG_LEVEL: INFO
LOG_FILE: mega-linter.log

# Additional Options
FLAVOR_SUGGESTIONS: true
SHOW_ELAPSED_TIME: false
SHOW_SKIPPED_LINTERS: true`;

    fs.writeFileSync(
      path.join(projectPath, '.mega-linter.yml'),
      megalinterConfig
    );

    // Create schemas directory
    const schemasDir = path.join(projectPath, 'schemas');
    if (!fs.existsSync(schemasDir)) {
      fs.mkdirSync(schemasDir);
    }

    await dataLake.close();

    console.log(chalk.green('✅ Project initialized successfully!'));
    console.log(chalk.yellow('📁 Project path:'), projectPath);
    console.log(chalk.yellow('🗄️  Database:'), 'carbonara.db');
    console.log(chalk.yellow('⚙️  Config:'), 'carbonara.config.json');
    console.log(chalk.yellow('🔧 MegaLinter:'), '.mega-linter.yml');
    console.log('');
    console.log(chalk.blue('Next steps:'));
    console.log(chalk.gray('  1. Run'), chalk.white('carbonara assess'), chalk.gray('to start CO2 assessment'));
    console.log(chalk.gray('  2. Run'), chalk.white('carbonara megalinter'), chalk.gray('to analyze code quality'));
    console.log(chalk.gray('  3. Run'), chalk.white('carbonara greenframe <url>'), chalk.gray('to analyze a website'));
    
  } catch (error) {
    console.error(chalk.red('❌ Failed to initialize project:'), error);
    process.exit(1);
  }
} 