// sample-data-insertion.ts
// This script demonstrates how to insert code highlight data into the carbonara.db
// Run this to add test data that will be displayed by the VSCode extension

import path from 'path';
import fs from 'fs';
import initSqlJs from 'sql.js';

// Sample code highlights that could be generated by analysis tools
const sampleHighlights = {
    tool_name: 'code_analysis',
    data_type: 'code_highlights',
    data: {
        highlights: [
            {
                file_path: 'src/extension.ts',
                start_line: 100,
                start_column: 1,
                end_line: 105,
                end_column: 50,
                severity: 'warning',
                message: 'This function creates multiple database connections. Consider using connection pooling to reduce energy consumption.',
                category: 'database-efficiency'
            },
            {
                file_path: 'src/extension.ts',
                start_line: 150,
                start_column: 5,
                end_line: 150,
                end_column: 80,
                severity: 'info',
                message: 'Consider lazy-loading this module to reduce initial load time and energy usage.',
                category: 'lazy-loading'
            },
            {
                file_path: 'src/database-highlighter.ts',
                start_line: 50,
                start_column: 1,
                end_line: 55,
                end_column: 30,
                severity: 'hint',
                message: 'This polling mechanism could be replaced with event-driven architecture for better efficiency.',
                category: 'architecture'
            }
        ],
        summary: {
            total_issues: 3,
            by_severity: {
                error: 0,
                warning: 1,
                info: 1,
                hint: 1
            }
        }
    },
    source: 'carbonara-analyzer'
};

// Alternative format: CO2 assessment with file-specific issues
const co2AssessmentHighlights = {
    tool_name: 'assessment',
    data_type: 'co2_analysis',
    data: {
        fileAnalysis: [
            {
                file: 'src/extension.ts',
                issues: [
                    {
                        line: 200,
                        column: 10,
                        endLine: 210,
                        endColumn: 50,
                        severity: 'warning',
                        message: 'This synchronous file operation blocks the main thread. Consider using async alternatives.'
                    },
                    {
                        line: 250,
                        column: 5,
                        severity: 'error',
                        message: 'Memory leak detected: Event listeners not being properly disposed.'
                    }
                ]
            },
            {
                file: 'src/database-highlighter.ts',
                issues: [
                    {
                        line: 100,
                        column: 1,
                        endLine: 120,
                        endColumn: 1,
                        severity: 'info',
                        message: 'Consider implementing caching to reduce database queries and save energy.'
                    }
                ]
            }
        ],
        totalScore: 75,
        recommendations: [
            'Implement connection pooling',
            'Use async file operations',
            'Add caching layer'
        ]
    },
    source: 'carbonara-co2-assessment'
};

async function insertSampleData() {
    const dbPath = path.resolve(process.cwd(), '../../carbonara.db');

    if (!fs.existsSync(dbPath)) {
        console.error(`Database not found at ${dbPath}`);
        console.log('Please ensure carbonara.db exists in the monorepo root');
        return;
    }

    const fileBuffer = fs.readFileSync(dbPath);
    const SQL = await initSqlJs();
    const db = new SQL.Database(fileBuffer);

    // First, get the project ID from the database
    const projectIdResult = db.exec('SELECT id FROM projects ORDER BY id DESC LIMIT 1');
    if (projectIdResult.length === 0 || !projectIdResult[0].values || projectIdResult[0].values.length === 0) {
        console.error('No project found in database. Please run "carbonara init" first.');
        return;
    }
    const projectId = projectIdResult[0].values[0][0];

    console.log(`Using project ID: ${projectId}`);

    // Insert the sample highlights
    try {
        [sampleHighlights, co2AssessmentHighlights].forEach(highlight => {
            const stmt = db.prepare(`
                INSERT INTO assessment_data (project_id, tool_name, data_type, data, source)
                VALUES (?, ?, ?, ?, ?)
            `);

            stmt.run([
                projectId,
                highlight.tool_name,
                highlight.data_type,
                JSON.stringify(highlight.data),
                highlight.source
            ]);

            stmt.free();
            console.log(`✅ Inserted ${highlight.tool_name} data`);
        });

        console.log('\n🎉 Sample data inserted successfully!');
        console.log('Now open VSCode and run the "Refresh Code Highlights" command to see the highlights.');

    } catch (error) {
        console.error('❌ Error inserting data:', error);
    } finally {
        const data = db.export();
        fs.writeFileSync(dbPath, data);
        db.close();
    }
}

// Run the insertion
insertSampleData().catch(console.error);
