# Non-compliant examples
img_jpg = "image.jpg"

def foo():
    # ...
    image_format = test_image("image.jpg")
    # ...

def foo():
    # ...
    return '<html><img src="xx/xx/image.bmp"></html>'
    # ...


# Compliant solutions
img_svg = "image.svg"

def foo():
    # ...
    image_format = test_image("image.svg")
    # ...

def foo():
    # ...
    return '<html><img src="xx/xx/image.svg"></html>'
    # ...

def foo():
    # ...
    return '<html><svg width="100" height="100"><circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow"/></svg></html>'
    # ...
