# Non-compliant examples
def foo():
    # ...
    base_query = "SELECT * FROM users"  # Noncompliant
    # ...


# Compliant solutions
def foo():
    # ...
    query = "SELECT id, name, address FROM users"
    # ...
